spring:
  application:
    name: api-all
  config:
    import:
      - optional:api-core.yml
      - optional:common.yml
      - optional:mysql.yml
      - optional:redis.yml

springdoc:
  swagger-ui:
    path: /api-docs

server:
  port: 8080